# https://travis-ci.org/HearthSim/python-mpq
sudo: false
language: python

python: "3.6"

env:
  - TOXENV=py36
  - TOXENV=flake8

cache: pip

install:
  - pip install --upgrade pip setuptools wheel
  - pip install tox

script:
  - tox

addons:
  apt:
    packages:
      - libstorm-dev

notifications:
  email:
    on_failure: always
    on_success: change
